### ISSUE TITLE
FEATURE: Put this animation on the homepage pre-wallet connect ASAP

### ISSUE THREAD

**Issue by rayraspberry** [Dracula-Protocol/frontend#16]
I think this video illustrates what DRC does for people and would help communicate the advantage of DRC to potential users.
Can we please feature this promenently on the homepage before users connect their wallet?   Above the Dashboard with deposits and everything else except TVL  - users can scroll down to see the extra stats or connect their wallet.

https://user-images.githubusercontent.com/83611789/117094699-16f02280-ad2a-11eb-8cc5-51b001a45185.mp4

This animation came from Studz in Telegram

**Comment by Cle4ncuts** [comment]
100% behind this. It'll make the value proposition of Dracula obvious at a glance to anyone entering our website. We need to convert traffic into stakers. Marketing will be working on articles to bring in LP farmers in the next couple of days.

**Comment by Khohezion** [comment]
I think this a pretty good idea.  Looking at this helped me understand how it works better haha.

**Comment by MantusNL** [comment]
Yes! I like it!

**Comment by sevenisalie** [comment]
love it! lets make it happen

**Comment by mdzor** [comment]
Nice one, closed as it has been added to our gitbook - our v2.1 frontend will come with a different landing page
