### ISSUE TITLE
URGENT:  Post Notice not to Stake due to Contract reissue / Block Deposits?

### ISSUE THREAD

**Issue by rayraspberry** [Dracula-Protocol/frontend#19]
I think it would be good to prevent deposits and have a notice posted to tell people not to stake until the contracts are re-issued.  Otherwise it seems people may become upset and frustrated that they are spending gas to stake for something without rewards and that they will need to unstake and restake shortly.

**Comment by rayraspberry** [comment]
![image](https://user-images.githubusercontent.com/83611789/117550820-f8c74280-b007-11eb-917d-4f5b43053f89.png)
devs are even saying "Don't Stake" -- this should be made very clear on the website

**Comment by mdzor** [comment]
removed deposits for farms, thanks for the feedback
