### ISSUE TITLE
Pool drawer cut off on screens < 480px width

### ISSUE THREAD

**Issue by nodatall** [Dracula-Protocol/frontend#2]
![dracula mobile ui bug](https://user-images.githubusercontent.com/12436787/116790002-f17fc200-aa66-11eb-85cc-d7a8210ee68d.png)

On screens less than 480px set width to 100%

**Comment by mdzor** [comment]
Hi thanks for reporting, this had been resolved already ![image](https://user-images.githubusercontent.com/7092335/116805225-882bac00-ab57-11eb-9f66-a9c8e4c238dc.png)
