### ISSUE TITLE
ISSUE: "Get [specific] LP" button on Pool Sidebar often do not point to correct swap / liquidity page

### ISSUE THREAD

**Issue by rayraspberry** [Dracula-Protocol/frontend#21]
Get Uniswap DRC-ETH LP token button goes to Uniswap V3  pool to add liquidity page, not incentivized V2 pool.
![image](https://user-images.githubusercontent.com/83611789/117575403-35964680-b0a7-11eb-88bb-4e6da518590b.png)
 points to this: https://app.uniswap.org/#/add/0xb78b3320493a4efaa1028130c5ba26f0b6085ef8/ETH

CORRECT LINK:   https://app.uniswap.org/#/add/v2/ETH/0xb78B3320493a4EFaa1028130C5Ba26f0B6085Ef8

Additional items make me think that possibly many pool links are effected.

Also reported by users:
```
For the sushi yCRV pool it says yCRV token, if you click on the link it has yyDAI+yUSDC+yUSDT+yTUSD-WETH. If you click on the Get link it asks for yUSD. For clarification it should be simplified to yUSD/ETH 

3. Get LP token links 

The following would give you the incorrect LP tokens 
Get ETH-USDC, for USDC, gives ETH/DODO 
I’m not clear if this only on my machine or what. When it first opens it takes me to ETH/USDC but when it finishes loading it take me to ETH/DODO. 
Dodo 
Include that you only need a single token (ETH, USDC, USDT, etc) for this pool 
```

**Comment by mdzor** [comment]
Fixed the issue of v2 links for Uniswap
Fixed the naming of yCRV to yUSD-ETH

For the last issue, it seem related to dodo website, will close the issue if you can reproduce and help point how can DRC resolve it
