### ISSUE TITLE
RFC:  Direct Contract Link on Website to Contract Addresses in Gitbook

### ISSUE THREAD

**Issue by rayraspberry** [Dracula-Protocol/frontend#25]
Reported by User:

`Usually when you click “contracts” it takes to you to the gitbook where all contracts are listed. If you click “contract” on the website it takes you to the masterVampire [etherscan webpage]. `

![image](https://user-images.githubusercontent.com/83611789/117580725-fd9afd80-b0be-11eb-9038-7260197228b6.png)

Gitbook URL: https://dracula-protocol.gitbook.io/dracula-protocol/developers/contract-addresses

**Comment by mdzor** [comment]
The contract is Mastervampire, which is the one linked (for easy access if someone wants to verify the hash while doing a transaction, you can just hover the link)

If you want to see all listed contract address it's on Github readme.md
