### ISSUE TITLE
Connecting Coinbasewallet 

### ISSUE THREAD

**Issue by fastnflex** [Dracula-Protocol/frontend#26]
There are protocol users, incl me, that facing problems with connecting a coinbase wallet to V2. We are using an IPhone. When trying to connect wallet the screen, send in the pucture, shows up. So we aren’t able to withdraw or stake tokens 
![FD98B8BE-A298-4FB6-A265-5A84863F948A](https://user-images.githubusercontent.com/84078842/117972226-24f60280-b32b-11eb-883a-6a8ea4978061.png)

**Comment by mdzor** [comment]
fixed, will be there for the next release

**Comment by fastnflex** [comment]
Thanks for the update Mdzor!

Meanwile we exported the eth adres to metamask and connected to the pool trough there. It was a good tip that came from the community

Op 14 mei 2021 om 18:03 heeft mdzor ***@***.***> het volgende geschreven:

﻿

fixed, will be there for the next release
