### ISSUE TITLE
Clicking on number in "Your Wallet" and "Your Deposit" should copy to clipboard or paste in input

### ISSUE THREAD

**Issue by nodatall** [Dracula-Protocol/frontend#4]
![image](https://user-images.githubusercontent.com/12436787/116791186-740b8000-aa6d-11eb-9400-af340de2facd.png)
Would be nice if clicking this number should past into input.

Also would look good to add commas and round this number.

**Comment by rayraspberry** [comment]
I agree with all these ideas / suggestions
