### ISSUE TITLE
QOL - Add buttons to allow staking 100% / 75% / etc of your coins

### ISSUE THREAD

**Issue by max-arias** [Dracula-Protocol/frontend#5]
Just a small QoL thing:
There's currently no way of stacking 100% / 75% / etc of your DRC/LP tokens, you have to write the amount manually.

**Comment by rayraspberry** [comment]
yes, I agree with this - [0%/clear] 25% 50% 75% [100%/Max]

**Comment by mdzor** [comment]
fixed in the latest version (just added the max button)
